# Generated by Django 4.2.28 on 2026-02-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_sprint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sprint',
            new_name='projects_sp_project_47cf99_idx',
            old_name='projects_sp_project_idx',
        ),
    ]
