# Generated by Django 4.2.11 on 2026-02-18 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='review_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='review_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('backlog', 'Backlog'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('archived', 'Archived')], max_length=20)),
                ('to_status', models.CharField(choices=[('backlog', 'Backlog'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('archived', 'Archived')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_status_changes', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='tasks.task')),
            ],
            options={
                'indexes': [models.Index(fields=['task', 'created_at'], name='tasks_tasks_task_id_e0a9d3_idx'), models.Index(fields=['to_status', 'created_at'], name='tasks_tasks_to_stat_7d0f2a_idx')],
            },
        ),
    ]
