# Generated by Django 4.2.28 on 2026-02-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_sprint_taskdependency'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_sprint__694521_idx',
            old_name='tasks_task_sprint_idx',
        ),
        migrations.RenameIndex(
            model_name='taskdependency',
            new_name='tasks_taskd_task_id_ec8227_idx',
            old_name='tasks_taskd_task_idx',
        ),
        migrations.RenameIndex(
            model_name='taskdependency',
            new_name='tasks_taskd_depends_7c20fd_idx',
            old_name='tasks_taskd_depends_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
    ]
