# Generated by Django 4.2.28 on 2026-02-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invitation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invitation',
            new_name='accounts_in_organiz_dba639_idx',
            old_name='accounts_in_organiz_idx',
        ),
        migrations.RenameIndex(
            model_name='invitation',
            new_name='accounts_in_token_894404_idx',
            old_name='accounts_in_token_idx',
        ),
    ]
