[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = --tb=short -v --cov=apps.accounts --cov=apps.organizations --cov=apps.projects --cov=apps.tasks --cov=apps.time_tracking --cov=apps.dashboard --cov=apps.core --cov=apps.notifications --cov=apps.performance --cov=apps.audit --cov-report=term-missing --cov-fail-under=80

[pytest:env]
DJANGO_ENV = test
