# Generated by Django 4.2.11 on 2026-02-18 12:10

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('feature_flags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('change_description', models.TextField()),
                ('change_payload', models.JSONField(default=dict, help_text='Serialized representation of the proposed change')),
                ('review_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='feature_flags.featureflag')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policies_approvalrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('production_owner_only', 'Only Owner can modify production'), ('production_approval', 'Production flags require approval'), ('archived_immutable', 'Archived flags cannot be edited'), ('key_immutable', 'Key cannot change after creation'), ('high_risk_dual_approval', 'High risk flags need dual approval')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='tenants.tenant')),
            ],
            options={
                'db_table': 'policies_policy',
                'ordering': ['policy_type'],
                'unique_together': {('tenant', 'policy_type')},
            },
        ),
    ]
