# Generated by Django 4.2.11 on 2026-02-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_organiz_155e59_idx',
            old_name='audit_audit_organiz_1c5c31_idx',
        ),
    ]
