# Generated by Django 4.2.28 on 2026-02-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_activityentry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activityentry',
            new_name='audit_activ_organiz_5a3c9e_idx',
            old_name='activity_org_created_idx',
        ),
        migrations.RenameIndex(
            model_name='activityentry',
            new_name='audit_activ_task_id_b655e1_idx',
            old_name='activity_task_created_idx',
        ),
    ]
