# Generated by Django 4.2.11 on 2026-02-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feature_flags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_key', models.CharField(db_index=True, max_length=255)),
                ('user_identifier', models.CharField(db_index=True, max_length=255)),
                ('evaluated_variant', models.JSONField(null=True)),
                ('environment_name', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_events', to='feature_flags.featureflag')),
            ],
            options={
                'db_table': 'analytics_evaluationevent',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['flag_key', '-timestamp'], name='analytics_e_flag_ke_4a1807_idx'), models.Index(fields=['flag', 'environment_name', '-timestamp'], name='analytics_e_flag_id_4fbf40_idx')],
            },
        ),
    ]
