# Generated by Django 4.2.11 on 2026-02-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feature_flags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('user_id', 'User ID'), ('role', 'Role'), ('country', 'Country'), ('custom_attribute', 'Custom Attribute'), ('email', 'Email'), ('percentage', 'Percentage')], max_length=30)),
                ('attribute_key', models.CharField(blank=True, default='', help_text='Attribute key for custom_attribute rule type', max_length=255)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Not Contains'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('in_list', 'In List'), ('not_in_list', 'Not In List'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('regex', 'Regex')], max_length=20)),
                ('value', models.JSONField()),
                ('variant_value', models.JSONField(blank=True, help_text='Variant to serve when rule matches', null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeting_rules', to='feature_flags.featureflag')),
            ],
            options={
                'db_table': 'targeting_targetingrule',
                'ordering': ['priority'],
            },
        ),
    ]
