# Generated by Django 4.2.28 on 2026-02-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_4e3567_idx',
            old_name='notif_recipient_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_organiz_f822ba_idx',
            old_name='notif_org_created_idx',
        ),
    ]
